version: '2'

services:
  todo:
    image: todo-app
    ports:
      - 8080:4000

  remote-control-app:
    image: remote-control-app
    ports:
      - 8110:4000

  websocket-server:
    image: websocket-server
    depends_on:
      - redis
    ports:
      - 8090:8080
    environment:
      REDIS_HOST: redis:6379

  redis:
    image: redis
    ports:
     - 6379:6379


  remote-control-server:
    image: remote-control-server
    depends_on:
      - redis
    ports:
      - 8100:8100
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

