version: '2'

services:
  todo-app:
    image: todo-app
    container_name: todo-app
    ports:
      - 8080:4000

  remote-control-app:
    image: remote-control-app
    container_name: remote-control-app
    ports:
      - 8110:5000
    environment:
      REMOTE_CONTROL_SERVER_BASE_URL: http://remote-control-server:8100

  websocket-server:
    image: websocket-server
    container_name: websocket-server
    depends_on:
      - redis
    ports:
      - 8090:8080
    environment:
      REDIS_HOST: redis:6379

  redis:
    image: redis
    container_name: redis
    ports:
     - 6379:6379

  remote-control-server:
    image: remote-control-server
    container_name: remote-control-server
    depends_on:
      - redis
    ports:
      - 8100:8100
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

