version: '2'

services:
  todo:
    image: todo-app
    ports:
     - 4000:4000

  websocket-server:
    image: websocket-server
    ports:
     - 8080:8080

  redis:
    image: redis
    ports:
     - 6379:6379
