apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: remote-controlled-pipeline
  spec:
    source:
      type: Git
      git:
        ref: pipeline
        uri: https://github.com/Mobenga/remote-controlled.git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
        - type: ConfigChange