apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: redhat-openjdk18-openshift
  spec:
    dockerImageRepository: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: redhat-nodejs6-openshift
  spec:
    dockerImageRepository: registry.access.redhat.com/rhscl/nodejs-6-rhel7
